### ISSUE TITLE
Icons & Images

### ISSUE THREAD

**Issue by alexspgn** [AlexSpagnuolo/portfolio#9]
Hey @thomasjbradley:

I'm having an issue with my images displaying on my Github link. I.e on my [gum packaging case study](https://alexspagnuolo.github.io/portfolio/gum-packaging/).

They show up fine on my localhost but they don't seem to show up there. I'm worried they won't show up when I publish my site, do you know what could be causing this?

Also, I'm still having an issues with my icons showing up when using use xlink, peep line 55 of my footer code in my _includes folder where I use this. You can see that one of the icons is missing in my footer for some reason. I'd like to have the ability to change the colour of my svg. The svgs are all #000

```
        <div class="unit xs-1-4 gutter">
          <a title="LinkedIn" itemprop="url" class="icon-link" href="https://www.linkedin.com/in/aaspagnuolo/" rel="me" rel="external">
            <i class="icon i-btn i-24">
              <svg><use xlink:href="{{site.baseurl}}/images/in.svg" /></svg>
            </i>
          </a>
        </div>
```

Thanks.

**Comment by thomasjbradley** [comment]
There are two fixes to get the LinkedIn icon showing:

1. Switch to using an `<img>` tag because the SVG isn’t a spritesheet.
2. Convert the SVG to a spritesheet with Spritebot and continue to use the `<svg><use>` tags.

---

The images on the Gum packaging page are broken because of capitalization—have a look at the filenames on this page here:
https://github.com/AlexSpagnuolo/portfolio/tree/master/images/gum-packaging

**Comment by alexspgn** [comment]
Thank you so much!
